version: '3'
services:
  dev:
    image: node:10-alpine
    volumes:
      - nodemodules:/root/KubeSphereUI/node_modules
      - .:/root/KubeSphereUI
    working_dir: /root/KubeSphereUI
    command: yarn start
    ports:
      - 8000:8000
      - 8001:8001

volumes:
  nodemodules:
    external: true
