version: '2'
services:
  base:
    image: node:10-alpine
    volumes:
      - nodemodules:/root/KubeSphereUI/node_modules
      - .:/root/KubeSphereUI
    working_dir: /root/KubeSphereUI

  install:
    extends:
      service: base
    command: yarn

  build:
    extends:
      service: base
    command: yarn build

volumes:
  nodemodules:
    external: true
