# kubesphere configuration

server:
  http:
    hostname: localhost
    port: 8000
    static:
      development:
        /public: server/public
        /assets: src/assets
        /build: build
        /dist: dist
      production:
        /public: server/public
        /assets: dist/assets
        /dist: dist

  # redis config for multi replicas
  # redis:
  #   port: 6379
  #   host: 127.0.0.1
  redisTimeout: 5000

  # kubesphere console session params, not login session
  sessionKey: 'kubesphere:sess'
  sessionTimeout: 3600000 # unit: millisecond

  # backend service gateway server
  apiServer:
    url: http://ks-apiserver.kubesphere-system.svc
    wsUrl: ws://ks-apiserver.kubesphere-system.svc

  # docker image search default url
  dockerHubUrl: https://hub.docker.com

client:
  title: KubeSphere
  description: ''

  version:
    kubesphere: 3.0.0

  # kubesphere urls
  issueUrl: https://github.com/kubesphere/kubesphere/issues/new/choose
  reposUrl: https://github.com/kubesphere/kubesphere
  slackUrl: https://kubesphere.slack.com
  documents:
    url: https://v3-0.docs.kubesphere.io/docs
    api: https://v3-0.docs.kubesphere.io/docs/api-reference/api-docs/

  # current support lanaguages
  supportLangs:
    - label: '繁體中文'
      value: 'tc'
    - label: '简体中文'
      value: 'zh'
    - label: 'English'
      value: 'en'
    - label: 'Español'
      value: 'es'
  defaultLang: 'en'

  # platform management navigations
  globalNavs:
    - name: clusters
      title: Clusters Management
      desc: CLUSTERS_MANAGE_DESC
      icon: cluster
    - name: access
      title: Access Control
      icon: key
      authKey: users|roles|workspaces
    - name: apps-manage
      title: App Store Management
      icon: openpitrix
      authKey: app-templates
      authAction: manage
      ksModule: openpitrix
    - name: settings
      title: Platform Settings
      icon: cogwheel
      authKey: platform-settings
      authAction: manage

  clusterNavs:
    - cate: cluster
      items:
        - name: overview
          title: Overview
          icon: dashboard
          skipAuth: true
          showInDisable: true
        - name: nodes
          title: Nodes Management
          icon: nodes
          children:
            - { name: nodes, title: Cluster Nodes }
        - { name: components, title: Service Components, icon: components }
        - { name: projects, title: NAV_PROJECTS, icon: project }
        - name: app-workloads
          title: Application Workloads
          icon: appcenter
          children:
            - name: workloads
              title: Workloads
              tabs:
                - { name: deployments, title: Deployments }
                - { name: statefulsets, title: StatefulSets }
                - { name: daemonsets, title: DaemonSets }
            - name: jobs
              title: Jobs
              tabs:
                - { name: jobs, title: Jobs }
                - { name: cronjobs, title: CronJobs }
            - { name: pods, title: Pods }
            - { name: services, title: Services }
            - { name: ingresses, title: Routes }
        - name: config
          title: Configuration Center
          icon: hammer
          children:
            - { name: secrets, title: Secrets }
            - { name: configmaps, title: ConfigMaps }
            - { name: serviceaccounts, title: ServiceAccounts }
        - name: network
          title: Network Management
          icon: earth
          children:
            - {
                name: networkpolicies,
                title: Network Policies,
                clusterModule: network,
              }
            - {
                name: ippools,
                title: IP Pools,
                clusterModule: 'network.ippool',
              }
        # Contains dangerous operations, only available for platform-admin.
        - {
            name: customresources,
            title: Custom Resources,
            icon: select,
            admin: true,
          }
        - name: storage
          title: Storage Management
          icon: database
          children:
            - { name: volumes, title: Volumes }
            - { name: volume-snapshots, title: Snapshots, authKey: volumes }
            - { name: storageclasses, title: Storage Classes }
        - name: monitoring-alerting
          title: Monitoring & Alerting
          icon: monitor
          children:
            - {
                name: monitor-cluster,
                title: Cluster Status,
                icon: linechart,
                authKey: monitoring,
              }
            - {
                name: monitor-resource,
                title: Application Resources,
                icon: linechart,
                authKey: monitoring,
              }
            - {
                name: alert-messages,
                title: Alerting Messages,
                icon: loudspeaker,
                clusterModule: 'alerting',
              }
            - {
                name: alert-policies,
                title: Alerting Policies,
                icon: hammer,
                clusterModule: 'alerting',
              }
            - { name: custom-monitoring, title: Custom Monitoring }
        - name: cluster-settings
          title: Cluster Settings
          icon: cogwheel
          showInDisable: true
          children:
            - {
                name: base-info,
                title: Basic Info,
                skipAuth: true,
                showInDisable: true,
              }
            - {
                name: visibility,
                title: Cluster Visibility,
                authKey: cluster-settings,
                multiCluster: true,
              }
            # - { name: members, title: Cluster Members }
            # - { name: roles, title: Cluster Roles }
            - {
                name: mail-server,
                title: Mail Server,
                icon: mail,
                authKey: cluster-settings,
                clusterModule: notification,
              }
            - {
                name: log-collections,
                title: Log Collections,
                icon: file,
                authKey: cluster-settings,
                clusterModule: logging|events|auditing,
              }

  # access control page navigations
  accessNavs:
    - cate: 'access'
      items:
        - { name: workspaces, title: Workspaces, icon: enterprise }
        - { name: accounts, title: NAV_ACCOUNTS, icon: human, authKey: users }
        - { name: roles, title: Account Roles, icon: role }

  # platform settings navigations
  platformSettingsNavs:
    - cate: 'platformsettings'
      items:
        - {
            name: base-info,
            title: Platform Info,
            icon: home,
            authKey: platform-settings,
          }

  # workspace page navigations
  workspaceNavs:
    - cate: 'workspace'
      items:
        - {
            name: overview,
            title: Overview,
            icon: dashboard,
            authKey: 'projects',
          }
        - name: projects
          title: NAV_PROJECTS
          icon: project
          skipAuth: true
          tabs:
            - { name: projects, title: Projects }
            - { name: federatedprojects, title: Multi-cluster Projects }
        - {
            name: devops,
            title: DevOps Projects,
            icon: strategy-group,
            ksModule: devops,
            skipAuth: true,
          }
        - name: apps
          title: Apps Management
          icon: appcenter
          children:
            - {
                name: apps,
                title: App Templates,
                icon: appcenter,
                authKey: app-templates,
                ksModule: openpitrix,
              }
            - {
                name: repos,
                title: App Repos,
                authKey: 'app-repos',
                ksModule: openpitrix,
              }
        - name: management
          title: Workspace Settings
          icon: cogwheel
          children:
            - { name: base-info, title: Basic Info, skipAuth: true }
            - { name: roles, title: Workspace Roles }
            - { name: members, title: Workspace Members }
            - { name: groups, title: Workspace Groups }

  # apps manage page navigations
  manageAppNavs:
    - cate: 'apps'
      items:
        - { name: store, title: App Store, icon: appcenter }
        - { name: categories, title: App Categories, icon: tag }
        - { name: reviews, title: App Review, icon: safe-notice }

  # project page navigations
  projectNavs:
    - cate: 'project'
      items:
        - {
            name: overview,
            title: Overview,
            icon: dashboard,
            authKey: 'services',
          }
        - name: app-workloads
          title: Application Workloads
          icon: appcenter
          children:
            - { name: applications, title: Applications, icon: application }
            - { name: services, title: Services }
            - name: workloads
              title: Workloads
              tabs:
                - { name: deployments, title: Deployments }
                - { name: statefulsets, title: StatefulSets }
                - { name: daemonsets, title: DaemonSets }
            - name: jobs
              title: Jobs
              tabs:
                - { name: jobs, title: Jobs }
                - { name: cronjobs, title: CronJobs }
            - { name: ingresses, title: Routes }
            - { name: pods, title: Pods }
        - name: storage
          title: Storage Management
          icon: database
          children:
            - { name: volumes, title: Volumes }
            - { name: volume-snapshots, title: Snapshots }
        - name: config
          title: Configuration Center
          icon: hammer
          children:
            - { name: secrets, title: Secrets }
            - { name: configmaps, title: ConfigMaps }
            - { name: serviceaccounts, title: ServiceAccounts }
        - {
            name: grayrelease,
            title: Grayscale Release,
            icon: bird,
            authKey: grayscale-release,
            clusterModule: servicemesh,
          }
        - {
            name: s2ibuilders,
            title: Image Builder,
            icon: vnas,
            clusterModule: devops,
          }
        - name: monitoring
          title: Monitoring & Alerting
          icon: monitor
          children:
            - {
                name: alert-messages,
                title: Alerting Message,
                clusterModule: alerting,
              }
            - {
                name: alert-policies,
                title: Alerting Policy,
                clusterModule: alerting,
              }
            - { name: custom-monitoring, title: Custom Monitoring }
        - name: settings
          title: Project Settings
          icon: cogwheel
          children:
            - { name: base-info, title: Basic Info, skipAuth: true }
            - {
                name: networkpolicies,
                title: Network Isolation,
                clusterModule: network,
                authKey: 'project-settings',
              }
            - { name: roles, title: Project Roles }
            - { name: members, title: Project Members }
            - {
                name: advanced,
                title: Advanced Settings,
                authKey: 'project-settings',
              }

  federatedProjectNavs:
    - cate: 'project'
      items:
        - { name: overview, title: Overview, icon: dashboard, skipAuth: true }
        - name: app-workloads
          title: Application Workloads
          icon: appcenter
          children:
            - { name: applications, title: Applications, icon: application }
            - { name: services, title: Services }
            - name: workloads
              title: Workloads
              tabs:
                - { name: deployments, title: Deployments }
                - { name: statefulsets, title: StatefulSets }
            - { name: ingresses, title: Routes }
        - { name: volumes, title: Volumes, icon: storage }
        - name: config
          title: Configuration Center
          icon: hammer
          children:
            - { name: secrets, title: Secrets }
            - { name: configmaps, title: ConfigMaps }
        - name: settings
          title: Project Settings
          icon: cogwheel
          children:
            - { name: base-info, title: Basic Info, skipAuth: true }
            - {
                name: quota,
                title: Quota Management,
                authKey: 'project-settings',
              }
            - {
                name: advanced,
                title: Advanced Settings,
                authKey: 'project-settings',
              }

  # devops page navigations
  devopsNavs:
    - cate: ''
      items:
        - { name: pipelines, title: Pipelines, icon: application }
        - name: management
          title: DEVOPS_PROJECT_MANAGEMENT
          icon: cogwheel
          open: true
          children:
            - { name: base-info, title: Basic Info, skipAuth: true }
            - { name: credentials, title: Credentials }
            - { name: roles, title: DEVOPS_PROJECT_ROLES }
            - { name: members, title: DEVOPS_PROJECT_MEMBERS }

  # system workspace rules control
  systemWorkspace: system-workspace
  systemWorkspaceRules:
    devops: []
    members: [manage]
    projects: [view, edit]
    roles: [view]
    workspaces: [view, edit]
  systemWorkspaceProjectRules:
    alerting: [manage]
    members: [manage]
    roles: [manage]
    custom-monitoring: [manage]

  # preset infos
  presetUsers: [admin, sonarqube]
  presetGlobalRoles:
    [platform-admin, platform-regular, workspaces-manager, users-manager]
  presetClusterRoles: [cluster-admin, cluster-viewer]
  presetWorkspaceRoles: [admin, regular, viewer, self-provisioner]
  presetDevOpsRoles: [admin, operator, viewer]
  presetRoles: [admin, operator, viewer]

  # system annotations that need to be hidden for edit
  preservedAnnotations: ['.*kubesphere.io/', 'openpitrix_runtime']

  # namespaces that need to be disable collection file log
  disabledLoggingSidecarNamespace: ['kubesphere-logging-system']

  # loadbalancer annotations, default support qingcloud lb
  loadBalancerDefaultAnnotations:
    service.beta.kubernetes.io/qingcloud-load-balancer-eip-ids: ''
    service.beta.kubernetes.io/qingcloud-load-balancer-type: '0'

  # control error notify on page
  enableErrorNotify: true

  # enable image search when add image for a container
  enableImageSearch: true

  # development
  # disable authorization check when developing
  disableAuthorization: false

  # show kubeconfig
  enableKubeConfig: true

  # third party tools
  thirdPartyTools:
    []
    # - title:
    #   description:
    #   link:

  # docs url for resources
  resourceDocs:
    # Project User Guide
    applications: /project-user-guide/application-workloads/app-template/
    composingapps: /project-user-guide/application-workloads/composing-app/
    deployments: /project-user-guide/application-workloads/deployments/
    statefulsets: /project-user-guide/application-workloads/statefulsets/
    daemonsets: /project-user-guide/application-workloads/daemonsets/
    jobs: /project-user-guide/application-workloads/jobs/
    cronjobs: /project-user-guide/application-workloads/cronjobs/
    services: /project-user-guide/application-workloads/services/
    ingresses: /project-user-guide/application-workloads/ingress/
    s2i_template: /project-user-guide/application-workloads/s2i-template/
    volumes: /project-user-guide/storage/volume/
    secrets: /project-user-guide/configuration/secrets/
    configmaps: /project-user-guide/configuration/configmaps/
    serviceaccounts: /project-user-guide/configuration/serviceaccounts/
    imageregistry: /project-user-guide/configuration/image-registry/
    grayrelease: /project-user-guide/grayscale/overview/

    # Project Administration
    internet: /project-administration/project-gateway/
    project_base_info: /project-administration/project-quota/
    project_roles: /project-administration/project-roles/
    project_members: /project-administration/project-members/

    # Cluster Administrator Guide
    nodes: /cluster-administration/nodes/
    storageclasses: /cluster-administration/storageclass/

    # DevOps User Guide
    pipelines: /devops-user-guide/introduction/pipeline/
    cridentials: /devops-user-guide/introduction/credential/

    # Developer Guide
    helm_specification: /application-store/app-developer-guide/helm-specification/
    helm_developer_guide: /application-store/app-developer-guide/helm-developer-guide/

    # Custom Console
    custom_console: /cluster-administration/platform-settings/customize-basic-information/

    # Kube Config
    kube_config: /multicluster-management/enable-multicluster/retrieve-kubeconfig/
  # devops:
  #  replace sonarqube link to customize url origin, default is useless
  # sonarqubeURL: http://139.123.123.123:8080
