name: Deploy-Backend

on:
  workflow_dispatch:

jobs:
  Deploy-Backend:
    runs-on: ubuntu-latest
    timeout-minutes: 150
    strategy:
      max-parallel: 1
    env:
      working-directory: ./.github/workflows/deploy-backend
    steps:
    - uses: actions/checkout@v2.1.1

    - name: setup terraform
      working-directory: ${{env.working-directory}}
      run: |
        wget https://releases.hashicorp.com/terraform/0.13.0/terraform_0.13.0_linux_amd64.zip
        unzip terraform_0.13.0_linux_amd64.zip

    - name: setup secret
      working-directory: ${{env.working-directory}}
      run: |
        sed -i 's/QING_ACCESS_KEY/${{ secrets.QINGCLOUD_ACCESS_KEY }}/g' var.tf
        sed -i 's/QING_SECRET_KEY/${{ secrets.QINGCLOUD_SECRET_KEY }}/g' var.tf
        sed -i 's/QING_EIP_ID/${{ secrets.QING_EIP_ID }}/g' var.tf
        sed -i 's/QING_EIP/${{ secrets.QING_EIP }}/g' var.tf
        sed -i 's/QING_PASSWORD/${{ secrets.QING_PASSWORD }}/g' var.tf
        sed -i 's/GITHUB_REPOSITORY/${{ github.repository_owner }}-tf-cd-console/g' var.tf

    - name: init
      working-directory: ${{env.working-directory}}
      run: |
        terraform init

    - name: destory
      working-directory: ${{env.working-directory}}
      continue-on-error: true
      run: |
        echo 'yes' | terraform destroy

    - name: install kubesphere
      working-directory: ${{env.working-directory}}
      timeout-minutes: 90
      run: |
        terraform apply -input=false -auto-approve
